version: "3"
services:
  react-app:
    image: symb/photon-client:1.0
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: symb/photon-server:1.0
    ports:
      - "3001:3001"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
